- hosts: localhost
  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
